name = "OpenScripturesHebrew"
uuid = "a2aa3e71-aced-403c-831b-dc7e729b9ba3"
authors = ["Neel Smith <dnsmith.neel@gmail.com>"]
version = "0.1.0"

[deps]
CitableBase = "d6f014bd-995c-41bd-9893-703339864534"
CitableText = "41e66566-473b-49d4-85b7-da83b66615d8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[compat]
CitableBase = "10"
CitableText = "0.16"
DocStringExtensions = "0.9"
Documenter = "1"
EzXML = "1"
TestSetExtensions = "2"
julia = "1.10, 1.11"
