---
title: OpenScripturesHebrew.jl
engine: julia
---


`OpenScripturesHebrew.jl` is a Julia package for working with the morphological data of the [Open Scriptures Hebrew Bible](https://hb.openscriptures.org) project (OSHB). `OpenScripturesHebrew.jl` parses the OSHB data into easily manipulated Julia tuples, and provides a Julia data model for the OSHB morphological data.


## Quickest start

### Download data
Get OSH annotations on all words in the Hebrew Bible:
```{julia}
#| warning: false
#| output: false
using OpenScripturesHebrew
words = tanakh()
```
```{julia}
length(words)
```


That's a lot of words!


### What's in a word

Each word is reprsented by a named tuple.

```{julia}
words[1]
```

In the tuple, the morphologically analyzed token is named `mtoken`:

```{julia}
words[1].mtoken
```

### Morphological analysis

The morphological analysis for the token is represented by a code string, but you can use the `parseword` function to create a `OSHMorphologicalForm`.

```{julia}
words[1].code
```

```{julia}
parseword(words[1])
```


### Select by canonical reference

Select words for a passage identified by the OSH name and passage conventions:

```{julia}
versewords = oshverse("Gen", "1.1", words)
```


### Apply regular Julia mapping to a selection of words

Extract the token and the morphological analysis from the tuple:


```{julia}
map(versewords) do w
    string(w.mtoken, " = ", parseword(w))
end
```

## More information

- See some [tutorials](./tutorials/) to get started
- See [reference documentation](./reference/) (APIs, data sources)


## Status

The package is not yet registered with the central Julia registry. You can directly add it to your Julia environment from its github repository [https://github.com/neelsmith/OpenScripturesHebrew.jl](https://github.com/neelsmith/OpenScripturesHebrew.jl). For example:

>
>```
>using Pkg
>Pkg.add(url = "https://github.com/neelsmith/OpenScripturesHebrew.jl")
>```
