
bookids = Dict(
    [
        "Gen" => "genesis",
        "Exod" => "exodus",
        "Lev" => "leviticus",
        "Num" => "numbers",
        "Deut" => "deuteronomy",

        "Josh" => "joshua",
        "Judg" => "judges",
        "Ruth" => "ruth", 
        "2Sam" => "2samuel",
        "1Kgs" => "1kings",
        "2Kgs" => "2kings",
        "2Chr" => "2chronicles",
        "Ezra" => "ezra",
        "Neh" => "nehemiah",
        "Esth" => "esther",
        "Job" => "job",
        "Ps" => "psalms",
        "Prov" => "proverbs",
        "Eccl" => "ecclesiastes",
        "Song" => "songs",
        "Isa" => "isaiah",
        "Jer" => "jeremiah",
        "Lam" => "lamentations",
        "Ezek" => "ezekiel",
        "Dan" => "daniel",
        "Hos" => "hosea",
        "Joel" => "joel", 
        "Amos" => "amos",
        "Obad" => "obadiah",
        "Jonah" => "jonah",
        "Mic" => "micah",
        "Nah" => "nahum",
        "Hab" => "habakkuk",
        "Zeph" => "zephaniah",
        "Hag" => "haggai",
        "Zech" => "zechariah",
        "Mal" => "malachi"
    ]
)   
